pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                echo 'clean package'
            }
        }
        stage('Test') {
            steps {
                echo 'test'
            }
        }
        stage('Deliver') { 
            steps {
                echo 'completed' 
            }
        }
    }
}
